version: '3.8'

networks:
  my-private-network:
    external: true

services:
  payment-db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paymentdb
    ports:
      - "3308:3306"
    volumes:
      - payment_db_data:/var/lib/mysql
    networks:
      - my-private-network

  payment-app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://payment-db:3306/paymentdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8082:8082"
    depends_on:
      - payment-db
    networks:
      - my-private-network
    volumes:
      - C:/Users/Perennial/Desktop/logs/payment:/app/logs  # Mounting the logs directory

volumes:
  payment_db_data:
